### ISSUE TITLE
Build fails on Mac

### ISSUE THREAD

**Issue by Tyil** [titsuki/p6-Terminal-Readsecret#15]
One of my modules ([`App::Assixt`](https://github.com/scriptkitties/perl6-app-assixt)) depends on `Terminal::Readsecret`, and a user has reported the following issue with this dependency on their Mac system:

```
===> Building: Terminal::Readsecret:ver<0.0.3>
readsecret.c:108:28: error: no member named 'si_int' in 'struct __siginfo'
        rsecret_got_timeout = si->si_int; /* timer id number */
                              ~~  ^
readsecret.c:177:
5: error: unknown type name 'timer_t'; did you mean 'time_t'?
    timer_t timer;
    ^~~~~~~
    time_t
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/sys/_types/_time_t.h:31:26: note: 'time_t' declared here
typedef __darwin_time_t         time_t;
                                ^
readsecret.c:237:7: warning: implicit declaration of function 'timer_create' is invalid in C99 [-Wimplicit-function-declaration]
        rc = timer_create( CLOCK_REALTIME, NULL, &timer );
             ^
readsecret.c:338:20: error: variable has incomplete type 'struct itimerspec'
        struct itimerspec itspec;
          ^
readsecret.c:338:9: note: forward declaration of 'struct itimerspec'
        struct itimerspec itspec;
               ^
readsecret.c:343:7: warning: implicit declaration of function 'timer_settime' is invalid in C99 [-Wimplicit-function-declaration]
        rc = timer_settime( timer, 0, & itspec, NULL );
             ^
readsecret.c:420:7: warning: implicit declaration of function 'timer_delete' is invalid in C99 [-Wimplicit-function-declaration]
        rc = timer_delete( timer );
             ^
3 warnings and 3 errors generated.
make: *** [/Users/justin/.zef/store/p6-Terminal-Readsecret.git/fe4119565632b1f5e9436fce1fe99143d9e16817/resources/libraries/libreadsecret.dylib] Error 1
```

**Comment by titsuki** [comment]
Thanks for reporting the issue!

Firstly to say, readsecret(https://github.com/dmeranda/readsecret) doesn't have compatibility with OSX.
So, it requires some modifications:
1) Unix and OSX have different structure of siginfo_t. To implement a workaround, it should call OSX version of `si_int` via `si_value.sival_int`.
2) Unlike Unix, OSX doesn't have timer stuffs (e.g., timer_create) that readsecret calls. I think that it should use mostly equivalent functions in OSX instead.

**Comment by titsuki** [comment]
@Tyil
In terms of portability, readsecret has a disadvantage; I decided to create another binding for getpass.c: http://repo.or.cz/w/glibc.git/blob/HEAD:/misc/getpass.c

Sorry for inconvenience.

**Comment by titsuki** [comment]
@Tyil 
OK. I made the getpass module. (getpass.c seems obsolete, so I use termios instead):
https://github.com/titsuki/p6-Terminal-Getpass

**Comment by titsuki** [comment]
@Tyil 
Sorry, this module doesn't work on OSX environment yet.
p6-Terminal-Getpass depends on term::termios and currently Term::termios isn't compatible with OSX.
It means that p6-Terminal-Getpass isn't compatible with OSX.
So, I'll fix Term::termios ASAP.

**Comment by titsuki** [comment]
I sent a PR:
https://github.com/krunen/term-termios/pull/11

**Comment by Tyil** [comment]
Thanks for the updates! I do not have any OSX machines myself, but I'll relay this information to the user that reported it to me (including the link to this ticket). Maybe it's easier if they can provide feedback directly.

**Comment by titsuki** [comment]
@Tyil
I updated.
This issue is solved since `Terminal::Getpass:auth<github:titsuki>:ver<0.0.5>`.

See also: https://github.com/titsuki/p6-Terminal-Getpass
