### ISSUE TITLE
Consider renaming to Terminal::Readsecret

### ISSUE THREAD

**Issue by ab5tract** [titsuki/p6-Terminal-Readsecret#3]
Because `term` has a specific definition within the Perl 6 language itself, myself and others decided to use the `Terminal` namespace for terminal-related modules in the ecosystem.

It is a stylistic choice, to be sure. But I wanted to raise the question.

**Comment by titsuki** [comment]
Thanks for good pointer.
I'll change the location of this repository.

**Comment by titsuki** [comment]
I have changed completely :)

**Comment by ab5tract** [comment]
Great! Thanks titsuki!
